services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    entrypoint: gcloud beta emulators pubsub start --project=qstorm-project --host-port=0.0.0.0:8095
    restart: unless-stopped
    ports:
      - "8095:8095"
