// Code generated by MockGen. DO NOT EDIT.
// Source: engine.go
//
// Generated by this command:
//
//	mockgen -source=engine.go -destination=mock/engine.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	config "github.com/nawafswe/qstorm/internal/config"
	metric "github.com/nawafswe/qstorm/internal/metric"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRenderer is a mock of templateRenderer interface.
type MocktemplateRenderer struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRendererMockRecorder
	isgomock struct{}
}

// MocktemplateRendererMockRecorder is the mock recorder for MocktemplateRenderer.
type MocktemplateRendererMockRecorder struct {
	mock *MocktemplateRenderer
}

// NewMocktemplateRenderer creates a new mock instance.
func NewMocktemplateRenderer(ctrl *gomock.Controller) *MocktemplateRenderer {
	mock := &MocktemplateRenderer{ctrl: ctrl}
	mock.recorder = &MocktemplateRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRenderer) EXPECT() *MocktemplateRendererMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MocktemplateRenderer) Render(queue config.QueueConfig) (config.QueueConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", queue)
	ret0, _ := ret[0].(config.QueueConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MocktemplateRendererMockRecorder) Render(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MocktemplateRenderer)(nil).Render), queue)
}

// Mockmessenger is a mock of messenger interface.
type Mockmessenger struct {
	ctrl     *gomock.Controller
	recorder *MockmessengerMockRecorder
	isgomock struct{}
}

// MockmessengerMockRecorder is the mock recorder for Mockmessenger.
type MockmessengerMockRecorder struct {
	mock *Mockmessenger
}

// NewMockmessenger creates a new mock instance.
func NewMockmessenger(ctrl *gomock.Controller) *Mockmessenger {
	mock := &Mockmessenger{ctrl: ctrl}
	mock.recorder = &MockmessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmessenger) EXPECT() *MockmessengerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Mockmessenger) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockmessengerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockmessenger)(nil).Close))
}

// Publish mocks base method.
func (m *Mockmessenger) Publish(ctx context.Context, queueConfig config.QueueConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, queueConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockmessengerMockRecorder) Publish(ctx, queueConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*Mockmessenger)(nil).Publish), ctx, queueConfig)
}

// MockmetricAggregator is a mock of metricAggregator interface.
type MockmetricAggregator struct {
	ctrl     *gomock.Controller
	recorder *MockmetricAggregatorMockRecorder
	isgomock struct{}
}

// MockmetricAggregatorMockRecorder is the mock recorder for MockmetricAggregator.
type MockmetricAggregatorMockRecorder struct {
	mock *MockmetricAggregator
}

// NewMockmetricAggregator creates a new mock instance.
func NewMockmetricAggregator(ctrl *gomock.Controller) *MockmetricAggregator {
	mock := &MockmetricAggregator{ctrl: ctrl}
	mock.recorder = &MockmetricAggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmetricAggregator) EXPECT() *MockmetricAggregatorMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockmetricAggregator) Record(executionTime time.Duration, encounteredErr error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", executionTime, encounteredErr)
}

// Record indicates an expected call of Record.
func (mr *MockmetricAggregatorMockRecorder) Record(executionTime, encounteredErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockmetricAggregator)(nil).Record), executionTime, encounteredErr)
}

// Snapshot mocks base method.
func (m *MockmetricAggregator) Snapshot() metric.Snapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].(metric.Snapshot)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockmetricAggregatorMockRecorder) Snapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockmetricAggregator)(nil).Snapshot))
}

// Summary mocks base method.
func (m *MockmetricAggregator) Summary() metric.Summary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary")
	ret0, _ := ret[0].(metric.Summary)
	return ret0
}

// Summary indicates an expected call of Summary.
func (mr *MockmetricAggregatorMockRecorder) Summary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockmetricAggregator)(nil).Summary))
}

// Mockprinter is a mock of printer interface.
type Mockprinter struct {
	ctrl     *gomock.Controller
	recorder *MockprinterMockRecorder
	isgomock struct{}
}

// MockprinterMockRecorder is the mock recorder for Mockprinter.
type MockprinterMockRecorder struct {
	mock *Mockprinter
}

// NewMockprinter creates a new mock instance.
func NewMockprinter(ctrl *gomock.Controller) *Mockprinter {
	mock := &Mockprinter{ctrl: ctrl}
	mock.recorder = &MockprinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockprinter) EXPECT() *MockprinterMockRecorder {
	return m.recorder
}

// Progress mocks base method.
func (m *Mockprinter) Progress(elapsed time.Duration, currentStage, totalStages, rate int, published, errors int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Progress", elapsed, currentStage, totalStages, rate, published, errors)
}

// Progress indicates an expected call of Progress.
func (mr *MockprinterMockRecorder) Progress(elapsed, currentStage, totalStages, rate, published, errors any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*Mockprinter)(nil).Progress), elapsed, currentStage, totalStages, rate, published, errors)
}
